# Generated by Django 4.1.7 on 2023-05-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment_score_alter_divingspot_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='divingspot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.divingspot', verbose_name='Punto de inmersión'),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
