# Generated by Django 4.1.7 on 2023-05-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divingspot',
            name='score',
            field=models.FloatField(default=0, verbose_name='Puntuación'),
        ),
    ]
