# Generated by Django 4.1.7 on 2023-05-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_divingspot_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='divingspot',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divingspot',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
