# Generated by Django 4.1.7 on 2023-05-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_comment_image_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment', verbose_name='Imagen'),
        ),
    ]
